# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddRegisterOtpAcceptUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_with_register_otp_accept, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:display_name, :text)
      add(:accepted_terms_at, :utc_datetime_usec)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:user_with_register_otp_accept, [:email],
             name: "user_with_register_otp_accept_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:user_with_register_otp_accept, [:email],
        name: "user_with_register_otp_accept_unique_email_index"
      )
    )

    drop(table(:user_with_register_otp_accept))
  end
end