# SPDX-FileCopyrightText: 2026 Alembic Pty Ltd
#
# SPDX-License-Identifier: MIT

defmodule Example.Repo.Migrations.AddMultitenantAuditLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mt_audit_logs, primary_key: false) do
      add(:resource, :text, null: false)
      add(:extra_data, :map, null: false, default: %{})
      add(:status, :text, null: false)
      add(:action_name, :text, null: false)

      add(:logged_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:audit_log, :text, null: false)
      add(:strategy, :text, null: false)
      add(:client_ip, :text)
      add(:identity, :text)
      add(:subject, :text)
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:organisation_id, :uuid)
    end

    create table(:mt_user_with_audit_log, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:organisation_id, :uuid, null: false)
      add(:email, :citext, null: false)
      add(:hashed_password, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:mt_user_with_audit_log, [:organisation_id, :email],
             name: "mt_user_with_audit_log_unique_email_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:mt_user_with_audit_log, [:organisation_id, :email],
        name: "mt_user_with_audit_log_unique_email_index"
      )
    )

    drop(table(:mt_user_with_audit_log))

    drop(table(:mt_audit_logs))
  end
end